# Data transformation


## Import Data

1) Index Price/Volulme/Return:

```{r}
library(tidyverse)
data_path <- "C:/Users/weili/Desktop/G5293/Final Project/Final_Project.xlsx"
readxl::excel_sheets(path = data_path)

SP500 <- readxl::read_excel(path=data_path,sheet=1)
Energy <- readxl::read_excel(path=data_path,sheet=2)
Info_tech <- readxl::read_excel(path=data_path,sheet=3)
Fin <-readxl::read_excel(path=data_path,sheet=4)
Health_care <- readxl::read_excel(path=data_path,sheet=5)
Consumer_D <- readxl::read_excel(path=data_path,sheet=6)
Utility <- readxl::read_excel(path=data_path,sheet=7)
Consumer_S <- readxl::read_excel(path=data_path,sheet=8)
Industrials <- readxl::read_excel(path=data_path,sheet=9)
Commu_Services <- readxl::read_excel(path=data_path,sheet=10)
Materials <- readxl::read_excel(path=data_path,sheet=11)
Real_Estate <- readxl::read_excel(path=data_path,sheet=12)
```

Pick several datasets to take a brief look at:

```{r}
head(SP500)
head(Energy)
head(Real_Estate)
```

2) S&P500 Constituents Financials:

```{r}
SP500_comp <- read.csv("C:/Users/weili/Desktop/G5293/Final Project/constituents_financials.csv")
SP500_sector <- readxl::read_xlsx("C:/Users/weili/Desktop/G5293/Final Project/500-sector-representation.xlsx",skip=3)
head(SP500_sector)
print(colnames(SP500_sector))
```

## Index Price/Volulme/Return:

### 1) Rename column names

Rename colnames to help distinguish

```{r}
colnames(SP500) <- c("Date","P_SP500","V_SP500","R_SP500")
colnames(Commu_Services) <- c("Date","P_CommuSer","V_CommuSer","R_CommuSer")
colnames(Consumer_D) <- c("Date","P_ConsumerD","V_ConsumerD","R_ConsumerD")
colnames(Consumer_S) <- c("Date","P_ConsumerS","V_ConsumerS","R_ConsumerS")
colnames(Energy) <- c("Date","P_Energy","V_Energy","R_Energy")
colnames(Fin) <- c("Date","P_Fin","V_Fin","R_Fin")
colnames(Health_care) <- c("Date","P_Health","V_Health","R_Health")
colnames(Industrials) <- c("Date","P_Industrial","V_Industrial","R_Industrial")
colnames(Info_tech) <- c("Date","P_Infotech","V_Infotech","R_Infotech")
colnames(Materials) <- c("Date","P_Materials","V_Materials","R_Materials")
colnames(Real_Estate) <- c("Date","P_RealEstate","V_RealEstate","R_RealEstate")
colnames(Utility) <- c("Date","P_Utility","V_Utility","R_Utility")
```

### 2) Merge into one dataset 

```{r}
USStock <- SP500%>%
  left_join(Commu_Services,by="Date")%>%
  left_join(Consumer_D,by="Date")%>%
  left_join(Consumer_S,by="Date")%>%
  left_join(Energy,by="Date")%>%
  left_join(Fin,by="Date")%>%
  left_join(Health_care,by="Date")%>%
  left_join(Industrials,by="Date")%>%
  left_join(Info_tech,by="Date")%>%
  left_join(Materials,by="Date")%>%
  left_join(Real_Estate,by="Date")%>%
  left_join(Utility,by="Date")
```


### 3) Seperate Price and Volume Data

```{r}
USStock_Price <- USStock%>%
  select(Date,starts_with("P_"))
USStock_Volume <- USStock%>%
  select(Date,starts_with("V_"))
USStock_Return <- USStock%>%
  select(Date,starts_with("R_"))
```


## S&P500 Constituents Financials:

```{r}
head(SP500_comp)
head(SP500_sector)
```

Rename column 

```{r}
SP500_sector <- SP500_sector%>%
  rename("Sector"="MARKET REPRESENTATION",
         "election_1"="election...6",
         "election_2"="election...9")%>%
  head(-2)
colnames(SP500_sector) <- gsub(" ","_",colnames(SP500_sector))
```