# Results

Start to explore

```{r}
library(tidyverse)
library(viridis)
Return_df <- pivot_longer(USStock_Return,!Date,
                         names_to = "Sector",
                         values_to = "Return")%>%
  group_by(Sector)

g1 <- ggplot(Return_df,aes(x=Date,y=Return,color=Sector))+
  geom_line()+
  labs(title = "US Stock Market Performance in the past 5 years",
       y="Return(%)")+
  theme_grey(12)+
  theme(legend.title = element_blank())
g1
```


```{r}
g2 <- ggplot(Return_df,aes(Return))+
  geom_histogram(color = "blue", fill = "lightblue")+
  facet_wrap(~Sector,scales = "free_x")
g2
```

```{r}
g3 <- ggplot(Return_df,aes(Return,Sector))+
  geom_boxplot()+
  labs(title="",
       x="Return (%)")+
  theme_grey(12)
g3
```

```{r}
library(ggridges)
g4 <- ggplot(Return_df,aes(x=Return,y=reorder(Sector,-Return,median)))+
  geom_density_ridges(fill="blue",alpha=0.5)+
  labs(title="",
       y="Sector",
       x="Return (%)")
g4
```


```{r}
head(USStock_Price)
tail(USStock_Price)

start_date <- "2017-01-06"


```

Info-tech perform best. 


### SP500 Constitutent

```{r}
head(SP500_comp)

```

```{r}
library(treemap)
head(SP500_sector)

#Treemap of 2021 Sector Composition
treemap(SP500_sector,index="Sector",vSize="2021",title = "SP500 Constituent in 2021")
```
```{r}
library(ggalluvial)
library(scales)

SP500_sector_year <- SP500_sector%>%
  select(c("Sector","1989","1999","2009","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"))%>%
  mutate(Sector=c("EN","M","I","CD","CS","HC","F","IT","CoS","U","RE"))

SP500_sector_year[,names(SP500_sector_year)!="Sector"]<- sapply(SP500_sector_year[,names(SP500_sector_year)!="Sector"],function(x) percent(x, accuracy=1))


gg_SP500_sector_year <- SP500_sector_year%>%
  to_lodes_form(axes=2:15)

al_plot <- ggplot(gg_SP500_sector_year,aes(alluvium=Sector,x=x,stratum=stratum))+
  geom_flow(aes(fill=Sector),width=1/12)+
  geom_stratum(color="black")+
  geom_text(stat = "stratum",aes(label=paste(after_stat(stratum))))+
  scale_y_continuous(expand = c(0.01,0))+
  theme_classic()
al_plot
```

```{r,echo=FALSE, fig.width = 10, fig.asp = .62}
library(vcd)

SP500_sector_situation <- SP500_sector%>%
  select(c("Sector","2021","2020","covid_low","election_1","pre-covid_hi"))%>%
  mutate(Sector=c("EN","M","I","CD","CS","HC","F","IT","CoS","U","RE"))


tidy_situation <- SP500_sector_situation%>%
  gather(key="Group",value="Freq",-Sector)

tidy_situation$Group <- fct_rev(tidy_situation$Group)

mosaic(Group~Sector, direction=c("h","v"),tidy_situation,
       highlighting_fill = c("grey80","cornflowerblue","lightblue","darkseagreen2","lightpink"))

```



```{r}
library(ggmosaic)


g5 <- ggplot(data=tidy_situation)+
  geom_mosaic(aes(x=product(Sector,Group),fill=Freq))
g5
```
### Specific Industry Analysis



```{r}
#Company correlation


```
